# Generated by Django 4.1.7 on 2023-02-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedanime',
            name='type',
            field=models.CharField(choices=[('FAVORITE', 'Favorite'), ('WATCHLATER', 'Watch Later'), ('WATCHED', 'Watched'), ('NONE', 'None')], default='NONE', max_length=20),
        ),
    ]
