# Generated by Django 4.1.7 on 2023-02-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_savedanime_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='anime_id',
            field=models.IntegerField(default=0),
        ),
    ]
