# Generated by Django 4.1.7 on 2023-02-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_anime_anime_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='description',
            field=models.TextField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='anime',
            name='image_url',
            field=models.TextField(default='', max_length=500),
        ),
    ]
